name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
        go-version: [1.22]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install Go dependencies [library]
        run: |
          cd pkg/geocode
          go mod download

      - name: Install Go dependencies [builder]
        run: |
          cd cmd/builder
          go mod download

      - name: Run Go tests [library]
        run: |
          cd pkg/geocode
          go test ./...

      - name: Run Go tests [builder]
        run: |
          cd cmd/builder
          go test ./...

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run Python tests
        run: |
          cd scripts
          pytest
